const palette = {
  primary: "#ccff00",
  secondary: "#0f172a",
  tertiary: "#1e293b",
  neutral: "#64748b",
  white: "#f8fafc",
  black: "#020617",
  success: "#5eead4",
  warning: "#fda4af",
};

export const colors = {
  light: {
    text: palette.white,
    textMuted: "#cbd5e1",
    textSoft: "#94a3b8",
    background: palette.secondary,
    backgroundCanvas: "#111827",
    surface: "#152238",
    surfaceRaised: "#1e2d46",
    surfaceMuted: palette.tertiary,
    border: "rgba(204,255,0,0.18)",
    borderStrong: "rgba(204,255,0,0.42)",
    tint: palette.primary,
    tabIconDefault: "#aeb9cf",
    tabIconSelected: palette.primary,
    cardAccent: palette.primary,
    cardHighlight: "#243652",
    metric: "#d8dcb8",
    searchBackground: "#1c2c44",
    destructive: palette.warning,
  },
  dark: {
    text: palette.white,
    textMuted: "#cbd5e1",
    textSoft: "#94a3b8",
    background: palette.secondary,
    backgroundCanvas: "#111827",
    surface: "#152238",
    surfaceRaised: "#1e2d46",
    surfaceMuted: palette.tertiary,
    border: "rgba(204,255,0,0.18)",
    borderStrong: "rgba(204,255,0,0.42)",
    tint: palette.primary,
    tabIconDefault: "#aeb9cf",
    tabIconSelected: palette.primary,
    cardAccent: palette.primary,
    cardHighlight: "#243652",
    metric: "#d8dcb8",
    searchBackground: "#1c2c44",
    destructive: palette.warning,
  },
};

export const colorPalette = palette;
